### ISSUE TITLE
Incomplete open source code？

### ISSUE THREAD

**Issue by lijigang525** [kevaldoshi17/Prediction-based-Video-Anomaly-Detection-#1]
Hello, I am a beginner in deep learning. I found that there is a lack of data preprocessing and the real training code. Is that true? The published code is almost the same as the open source code of the future frame.

**Comment by kevaldoshi17** [comment]
Hello. As mentioned in our paper, one of the statistics used in our feature vector is computed similarly to the future frame prediction algorithm. If you check the Jupyter notebook, you will find the real training code for our algorithm.
