### ISSUE TITLE
Real Time Code

### ISSUE THREAD

**Issue by vishalned** [kevaldoshi17/Prediction-based-Video-Anomaly-Detection-#4]
Hey, So I have noticed that the notebook that you have created makes use of the pre-generated psnr file. I know that we can create the bounding boxes using YOLO in real-time, but could you maybe release the code or give some suggestions on running the code on real-time, i.e without any pre-generated psnr results. Thanks in advance.

**Comment by kevaldoshi17** [comment]
Hi, to run the code in real-time, all you need to do is run the inference of the future frame algorithm for a given batch of input frames (like a sliding window) and use the psnr between the predicted and actual frame with the YOLO bounding boxes.

**Comment by vishalned** [comment]
got it, thanks.

**Comment by mausLe** [comment]
> Hi, to run the code in real-time, all you need to do is run the inference of the future frame algorithm for a given batch of input frames (like a sliding window) and use the psnr between the predicted and actual frame with the YOLO bounding boxes.

Hi @kevaldoshi17 
How could I integrate the inference, YOLO, and the MONAD notebook to run these in real-time?

**Comment by Zain-Gill123** [comment]
Hey @mausLe !
Did you find how to run the Inference, YOLO and MONAD notebook in Real-Time? 
Cheers!

**Comment by mausLe** [comment]
Hi @Zain-Gill123 
I had not found any way to run it in real-time. 
The average FPS when I ran it on RTX 3090 was about 14 FPS.

**Comment by Zain-Gill123** [comment]
Thanks @mausLe !
Thank you for helping. Would mind sharing that notebook with me? You have already shared one with me, is it the same one?
Cheers!

**Comment by mausLe** [comment]
@Zain-Gill123 Yeah it is.
