### ISSUE TITLE
Monad.ipynb

### ISSUE THREAD

**Issue by vishalned** [kevaldoshi17/Prediction-based-Video-Anomaly-Detection-#5]
Hey, could you please explain what this specific snippet of code does? in particular, I am not able to understand the use of the limits 10, 54, and 6.

![image](https://user-images.githubusercontent.com/27778126/112195203-1e001d00-8c23-11eb-8d99-376087e86065.png)

**Comment by kevaldoshi17** [comment]
That particular snippet of code is to clean the generated output, so for example if in a given window of 10 frames less than 6 have an increase, then most likely those are false alarms. The first and third for loops are basically the same, you can remove one of them.

**Comment by vishalned** [comment]
Thanks for the clarification
